# -------------------------------------------------------------------
# DEV environment overrides
# - reduced scale
# - cheaper resources
# - higher verbosity
# -------------------------------------------------------------------

replicaCount: 1

autoscaling:
  minReplicas: 1
  maxReplicas: 2

resources:
  limits:
    cpu: 300m
    memory: 256Mi

additionalArguments:
  # Entrypoints
  - "--entryPoints.web.address=:80"
  - "--entryPoints.websecure.address=:443"
  - "--entryPoints.websecure.http.tls=false"

  # Global HTTP â†’ HTTPS redirect
  - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
  - "--entryPoints.web.http.redirections.entryPoint.scheme=https"

  # Security / API
  - "--api.dashboard=false"
  - "--api.insecure=false"

  # Logging (DEV override)
  - "--log.level=DEBUG"
