provider: cloudflare

sources:
  - service

domainFilters:
  - ccore.ai

policy: upsert-only

registry: txt
txtOwnerId: eks-gitops

interval: 5m
logLevel: info

image:
  repository: registry.k8s.io/external-dns/external-dns
  tag: v0.19.0

serviceAccount:
  create: true
  name: external-dns

rbac:
  create: true

serviceMonitor:
  enabled: false

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: CF_API_TOKEN
