apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: aws-default
spec:
  instanceProfile: eks-platform-dev-karpenter-node

  amiSelectorTerms:
    - alias: al2023@latest

  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-platform-dev-cluster

  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-platform-dev-cluster
